// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
import DropdownController from "./dropdown_controller"
import MobileMenuController from "./mobile_menu_controller"

application.register("accordion", AccordionController)
application.register("dropdown", DropdownController)
application.register("mobile-menu", MobileMenuController)
