FactoryBot.define do
  factory :user do
    sequence(:email) { |n| "user#{n}@example.com" }
    password { "password123" }
    first_name { Faker::Name.first_name }
    last_name { Faker::Name.last_name }
    company_name { Faker::Company.name }
    phone { Faker::PhoneNumber.phone_number }
    title { "Interior Designer" }

    # api_token is auto-generated by has_secure_token

    trait :without_profile do
      first_name { nil }
      last_name { nil }
      company_name { nil }
      phone { nil }
      title { nil }
    end
  end
end
